name: Docker Image Security Scan
on: [push]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  

      - name: Scan and Generate Report
        run: |
          docker run --rm aquasec/trivy image \
            --severity CRITICAL\
            --exit-code 1 \
            --format table \
            vulnerables/web-dvwa | tee trivy-report.txt
          echo "Vulnerabilidades encontradas (workflow configurado para fallar)"

      - name: Upload Report
        if: always()
        uses: actions/upload-artifact@v4  # ¡Versión corregida!
        with:
          name: trivy-results
          path: trivy-report.txt
